### Recibir
GET http://localhost:1234/pokemon/ditto

### Enviar
POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name": "ditto",
    "type": "normal",
    "moves": [
        "transform"
    ]
}